### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by eileenmcnaughton** [civicrm/api4#33] opened 2017-02-15 09:46 UTC
I downloaded the api & as step number 1 ran the tests. They do not currently pass - due to a change @colemanw added recently to set the default for check_permissions to be TRUE.

Both getActions and the get call are failing

I would suggest we set the tests to use setCheckPermssions = FALSE so they pass again since we should always have the tests in a passing state & this is a new barrier

**Comment by eileenmcnaughton** [comment] 2017-02-15 09:51
OK this didn't work

    $result = Participant::getActions()
      ->execute()
      ->setCheckPermissions(FALSE)
      ->indexBy('name');

@colemanw I think you should revert your permissions commit until we can get the tests to work with it - I think it's a blocker now

**Comment by colemanw** [comment] 2017-02-15 13:56
I think the problem is you are executing and settingCheckPermissions in 
the wrong order.

**Comment by eileenmcnaughton** [comment] 2017-02-15 20:11
Fixes that test but not this

    // test behaviour with no records:
    $call = Participant::get()
      ->setCheckPermissions(FALSE)
      ->setLimit(5);
    $empty_result = $call->execute();
    $this->assertEquals(0, count($empty_result),
      "count of empty get is not 0");

**Comment by ErichBSchulz** [comment] 2017-02-20 06:56
oops sorry this has my fingerprints on it! will work on this now!

**Comment by ErichBSchulz** [comment] 2017-02-20 06:59
@eileenmcnaughton re your `$this->assertEquals(0, count($empty_result), "count of empty get is not 0");`

are you expecting a get with no `where`'s to return 0 records??

**Comment by eileenmcnaughton** [comment] 2017-02-20 07:14
Probably - I didn't write that test - but it seems to be a 'no errors happen' test - which is a legit test - although on it's own is pretty poor coverage :-)

**Comment by ErichBSchulz** [comment] 2017-02-28 03:33
all tests should now be passing @eileenmcnaughton

**Comment by ErichBSchulz** [comment] 2017-02-28 03:34
urg and I'm not permitted to close this issue :-/

**Closed** 2017-02-28 04:20 UTC
